// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZeDcstSjpBx1LQ2zrcMf4L8nkRNJ3DY8',
    appId: '1:918022856169:web:b0f544deee57b17d647f78',
    messagingSenderId: '918022856169',
    projectId: 'boardingease-506f1',
    authDomain: 'boardingease-506f1.firebaseapp.com',
    storageBucket: 'boardingease-506f1.appspot.com',
    measurementId: 'G-PJ7DF1CMGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwMFxCwufwiF78LvNPTvi-YwDe3Isc1s',
    appId: '1:918022856169:android:53dc2b1b65a0c3ef647f78',
    messagingSenderId: '918022856169',
    projectId: 'boardingease-506f1',
    storageBucket: 'boardingease-506f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbQRtsPQPEmpRiNn0d4YFFfX1zeBw-Fw',
    appId: '1:918022856169:ios:cab058a67fb63ea3647f78',
    messagingSenderId: '918022856169',
    projectId: 'boardingease-506f1',
    storageBucket: 'boardingease-506f1.appspot.com',
    iosBundleId: 'com.example.boardingEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbQRtsPQPEmpRiNn0d4YFFfX1zeBw-Fw',
    appId: '1:918022856169:ios:0a63375321a2cf2e647f78',
    messagingSenderId: '918022856169',
    projectId: 'boardingease-506f1',
    storageBucket: 'boardingease-506f1.appspot.com',
    iosBundleId: 'com.example.boardingEase.RunnerTests',
  );
}
